# lambdaForTestingGithub/pyproject.toml
[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lambdaForTestingGithub"
version = "0.0.1"

[tool.setuptools]
package-dir = {"" = "src"}
py-modules = ["lambda_funktion"]
