name: AWS_test

on: 

  push:

    branches: [main]

jobs: 

  test:

    runs-on: ubuntu-latest

    steps:

      - name: checkout repository
        uses:  actions/checkout@v4
      
      - name: set up Python
        #bei uses braucht man immer eine version .zB @4 oder @5 jenach verwendetem Program 
        uses: actions/setup-Python@v5 
        with:
          python-version: "3.12"

      - name: Install dependencies for test (if any)
        run: | 
         
          # Projektabh채ngigkeitspr체fung
          python -m pip install --upgrade pip 
          pip install pytest
          pip install boto3
          pip install moto 
          if [ -f lambdaForTestingGithub/requirements.txt ]; then
            pip install -r lambdaForTestingGithub/requirements.txt
          elif [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else 
            echo "No requirements found -> continuing"
          fi 

   
          
          # installiere das lokale Paket editierbar, damit Imports funktionieren
          pip install -e ./lambdaForTestingGithub || true

      - name: Run pytest
        # damit die lambda-pkg-src importierbar ist, falls die tests die src-Module nutzen
        env:
          PYTHONPATH: lambdaForTestingGithub/src
        run: | 

          mkdir -p test-reports 
          # f체hre alle Tests im Repo aus (passt, wenn tests/ oder projekt-root Tests enth채lt)
          pytest -q --junitxml=test-reports/junit.xml -rA

      - name: Uploud test reporte
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: test-reports/

  deploy: 
    needs: test
    runs-on: ubuntu-latest

    env:
      FUNCTION_NAME: labdaForTestingGithub
      REGION: eu-north-1
      ZIP_NAME: labdaForTestingGithub.zip

    steps: 
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Debug workspace (optional, hilft bei Pfadproblemen)
        run: |
          pwd
          ls -la
          ls -la zl_create_user_json_iot || true
          ls -la zl_create_user_json_iot/src || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (if any)
        working-directory: ./lambdaForTestingGithub
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt -t src/
          else
            echo "No requirements.txt -> skipping dependency install"
            mkdir -p src
          fi




