name: AWS_test

on: 

  push:

    branches: [main]

jobs: 

  test:

    runs-on: ubuntu-latest

    steps:

      - name: checkout repository
        uses:  actions/checkout@v4
      
      - name: set up Python
        #bei uses braucht man immer eine version .zB @4 oder @5 jenach verwendetem Program 
        uses: actions/setup-Python@v5 
        with:
          python-version: "3.12"
        
      - name: Install dependencies
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip

          # 1) requirements finden und installieren (Repo-Root ODER Unterordner)
          REQ_FILE=""
          if [ -f lambdaForTestingGithub/requirements.txt ]; then
            REQ_FILE="lambdaForTestingGithub/requirements.txt"
          elif [ -f requirements.txt ]; then
            REQ_FILE="requirements.txt"
          fi

          if [ -n "${REQ_FILE}" ]; then
            echo "Installing from ${REQ_FILE}"
            pip install -r "${REQ_FILE}"
          else
            echo "No requirements.txt found -> installing minimal test deps"
            pip install pytest boto3 moto
          fi

          # 2) Nur dann editable install, wenn Paket-Metadaten vorhanden sind
          if [ -f lambdaForTestingGithub/pyproject.toml ] || [ -f lambdaForTestingGithub/setup.py ]; then
            pip install -e ./lambdaForTestingGithub
          else
            echo "No pyproject.toml/setup.py -> skipping editable install"
          fi


      - name: Run pytest
        env:
          PYTHONPATH: lambdaForTestingGithub/src
        run: |
          mkdir -p test-reports
          pytest -q --junitxml=test-reports/junit.xml -rA
        




