name: AWS_test

on: 

  push:

    branches: [main]

jobs: 

  test:

    runs-on: ubuntu-latest

    steps:

      - name: checkout repository
        uses:  actions/checkout@v4
      
      - name: set up Python
        uses: actions/setup-Python@v5
        with:
          python-version: "3.12"
        
      - name: Install dependencies for test (if any)
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install boto3
          pip install moto
          # Projektabhängigkeitsprüfung
          if [ -f lambdaForTestingGithub/requirements.txt ]; then
            pip install -r lambdaForTestingGithub/requirements.txt
          elsif [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else 
            echo "No requirements found" -> continuing"
          fi

        




